name = "Hugo's Resume"
license = "MIT"
licenselink = "https://github.com/schebotar/hugos-resume/blob/master/LICENSE"
description = "Hugo resume theme inspired by Jake's resume"
homepage = "https://github.com/schebotar/hugos-resume/"
demosite = "https://schebotar.github.io/hugos-resume/"
tags = ["resume", "minimal"]
min_version = "0.41.0"

[author]
  name = "Serghei Cebotari"
  homepage = "https://cebotari.ru"